language: java
jdk:
  - openjdk8

script:
  # Build the application
  - javac -d bin -cp lib/itextpdf.jar src/chiffrement/* src/modeleAES/* src/modeleDES/* src/Outils/* src/Fenetre.java src/Principale.java
